version: "3"
services:
    chess-pgnator:
        build: ./front-end
        container_name: chess-pgnator
        volumes:
            - build_react:/var/www/html

    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - build_react:/var/www/html
        depends_on:
            - chess-pgnator

volumes:
    build_react:
